#!/usr/bin/env bash
set -o errexit
########################################################################################################
## global logging fuction
########################################################################################################
function logger_ngseasy() {
 message=${1}
 mylogfile=${2}
 echo -e [`date`]":[NGSEASY:${NGSEASYVERSION}]:"${message}":[${USER}]:[`uname -a`]" >> ${mylogfile}.log;
 echo -e [`date`]":[NGSEASY:${NGSEASYVERSION}]:"${message}":[${USER}]:[`uname -a`]"
}

########################################################################################################
## test if docker installed and exit if not
########################################################################################################
function docker_installed(){
    command -v docker >/dev/null 2>&1 || { echo -e "\n\nDocker not installed.\n\nAborting....." >&2; exit 1; }
    echo -e "Docker Installed ok"
    echo -e "Checking Docker Version and Info\n"
    DOCKERVERSION=`docker version`
    DOCKERINFO=`docker info`
    echo -e "\n----\nDocker Version\n----\n${DOCKERVERSION}\n----\n"Docker Info"\n----\n${DOCKERINFO}\n----\n"
    echo -e [`date`]":[NGSEASY:${NGSEASYVERSION}]:"[Log:START]":[${USER}]:[`uname -a`]"
    sleep 1s
}
